[default]
mongo_uri = "mongodb://localhost:27017/blog"
title = "Bloguizinho"
extensions = [
    "blog.database:configure",
    "blog.commands:configure",
    "flask_bootstrap:Bootstrap",
    "blog.views:configure",
]
